export type Dish = {
  id: string;
  code?: string;
  name: string;
  namePt?: string;
  description: string;
  descriptionPt?: string;
  price: number;
  calories: number;
  imageId: string;
};

export type MenuCategory = {
  id: "sushi" | "sashimi" | "warm" | "hotpot" | "desserts";
  label: string;
  labelJp?: string;
  tagline: string;
  dishes: Dish[];
};

export const menu: MenuCategory[] = [
  {
    id: "sushi",
    label: "Sushi",
    labelJp: "寿司",
    tagline: "Hand-formed daily. Knife-cut to order.",
    dishes: [
      {
        id: "SN",
        name: "Salmon Nigiri",
        namePt: "Nigiri de Salmão",
        description: "Two pieces. Norwegian salmon, shari, a breath of wasabi.",
        descriptionPt: "Duas peças. Salmão norueguês, shari, um toque de wasabi.",
        price: 3.5,
        calories: 95,
        imageId: "SN",
      },
      {
        id: "TN",
        name: "Tuna Nigiri",
        namePt: "Nigiri de Atum",
        description: "Two pieces. Yellowfin, cut against the grain.",
        descriptionPt: "Duas peças. Atum-albacora, cortado contra o veio.",
        price: 3.8,
        calories: 90,
        imageId: "TN",
      },
      {
        id: "EN",
        name: "Ebi Nigiri",
        namePt: "Nigiri de Camarão",
        description: "Two pieces. Butterflied prawn, lightly poached.",
        descriptionPt: "Duas peças. Camarão escalfado, aberto em borboleta.",
        price: 3.2,
        calories: 80,
        imageId: "EN",
      },
      {
        id: "DR",
        name: "Dragon Roll",
        description: "Eight pieces. Eel, cucumber, avocado over rice, unagi glaze.",
        descriptionPt: "Oito peças. Enguia, pepino, abacate, glace unagi.",
        price: 12.0,
        calories: 480,
        imageId: "DR",
      },
      {
        id: "RR",
        name: "Rainbow Roll",
        description: "Eight pieces. California base crowned with salmon, tuna, yellowtail.",
        descriptionPt: "Oito peças. Base California coroada com salmão, atum, seriola.",
        price: 13.5,
        calories: 520,
        imageId: "RR",
      },
      {
        id: "ST",
        name: "Spicy Tuna Roll",
        description: "Eight pieces. Chopped tuna, sriracha, togarashi crunch.",
        descriptionPt: "Oito peças. Atum picado, sriracha, togarashi crocante.",
        price: 10.0,
        calories: 420,
        imageId: "ST",
      },
    ],
  },
  {
    id: "sashimi",
    label: "Sashimi",
    labelJp: "刺身",
    tagline: "Fish first. Nothing else in the way.",
    dishes: [
      {
        id: "SS",
        name: "Salmon Sashimi",
        namePt: "Sashimi de Salmão",
        description: "Eight slices. Served over shaved ice with wasabi root.",
        descriptionPt: "Oito fatias. Servido sobre gelo com raiz de wasabi.",
        price: 14.0,
        calories: 240,
        imageId: "SS",
      },
      {
        id: "CP",
        name: "Chef's Platter",
        namePt: "Travessa do Chef",
        description: "Twenty pieces. The kitchen chooses. Always the best of the ice.",
        descriptionPt: "Vinte peças. Seleção do chef. Sempre o melhor do dia.",
        price: 28.0,
        calories: 980,
        imageId: "CP",
      },
    ],
  },
  {
    id: "warm",
    label: "Warm Dishes",
    labelJp: "温菜",
    tagline: "Wok-fired. Cantonese technique, a Madeira table.",
    dishes: [
      {
        id: "P1",
        code: "P1",
        name: "Spicy Chicken",
        namePt: "Frango Picante",
        description: "Wok-tossed chicken, dried chilies, Sichuan pepper.",
        descriptionPt: "Frango saltado no wok, malaguetas secas, pimenta de Sichuan.",
        price: 7.5,
        calories: 510,
        imageId: "P1",
      },
      {
        id: "P2",
        code: "P2",
        name: "Sweet & Sour Chicken",
        namePt: "Frango Agridoce",
        description: "Crisp chicken, pineapple, bell pepper, house agridoce.",
        descriptionPt: "Frango crocante, ananás, pimento, molho agridoce da casa.",
        price: 7.5,
        calories: 590,
        imageId: "P2",
      },
      {
        id: "P3",
        code: "P3",
        name: "Chicken with Bamboo & Mushrooms",
        namePt: "Frango com Bambú e Cogumelos",
        description: "Silken chicken, bamboo shoots, shiitake, light soy.",
        descriptionPt: "Frango tenro, rebentos de bambú, shiitake, soja suave.",
        price: 7.5,
        calories: 440,
        imageId: "P3",
      },
      {
        id: "P4",
        code: "P4",
        name: "Chicken with Almonds",
        namePt: "Frango com Amêndoas",
        description: "Chicken, toasted almonds, spring onion, a whisper of oyster sauce.",
        descriptionPt: "Frango, amêndoas tostadas, cebolinho, molho de ostra.",
        price: 7.5,
        calories: 560,
        imageId: "P4",
      },
      {
        id: "P5",
        code: "P5",
        name: "Lemon Chicken",
        namePt: "Frango ao Limão",
        description: "Crisp-skinned chicken, Amalfi lemon glaze.",
        descriptionPt: "Frango de pele estaladiça, glace de limão Amalfi.",
        price: 7.5,
        calories: 530,
        imageId: "P5",
      },
      {
        id: "P6",
        code: "P6",
        name: "Beef with Bamboo & Mushrooms",
        namePt: "Vaca com Bambú e Cogumelos",
        description: "Tender beef, bamboo, shiitake, dark soy reduction.",
        descriptionPt: "Vaca tenra, bambú, shiitake, redução de soja escura.",
        price: 8.5,
        calories: 610,
        imageId: "P6",
      },
      {
        id: "P7",
        code: "P7",
        name: "Spicy Beef",
        namePt: "Bife Picante",
        description: "Flash-seared beef, fresh chili, garlic, black pepper.",
        descriptionPt: "Vaca selada rápido, malagueta fresca, alho, pimenta preta.",
        price: 8.5,
        calories: 640,
        imageId: "P7",
      },
      {
        id: "P9",
        code: "P9",
        name: "Peking Duck",
        namePt: "Pato de Pequim",
        description: "Lacquered duck, scallion, cucumber, thin pancakes.",
        descriptionPt: "Pato laqueado, cebolinho, pepino, panquecas finas.",
        price: 8.5,
        calories: 680,
        imageId: "P9",
      },
      {
        id: "P10",
        code: "P10",
        name: "Duck à l'Orange",
        namePt: "Pato com Laranja",
        description: "Pan-seared duck breast, blood orange reduction.",
        descriptionPt: "Peito de pato selado, redução de laranja sanguínea.",
        price: 9.0,
        calories: 590,
        imageId: "P10",
      },
      {
        id: "P11",
        code: "P11",
        name: "Clams",
        namePt: "Ameijoa",
        description: "Clams, garlic, coriander, Madeira white wine.",
        descriptionPt: "Ameijoas, alho, coentros, vinho branco da Madeira.",
        price: 6.8,
        calories: 220,
        imageId: "P11",
      },
      {
        id: "P12",
        code: "P12",
        name: "Salt & Pepper Prawns",
        namePt: "Camarão com Sal e Pimenta",
        description: "Shell-on prawns, Sichuan salt, white pepper, spring onion.",
        descriptionPt: "Camarão com casca, sal de Sichuan, pimenta branca, cebolinho.",
        price: 8.9,
        calories: 380,
        imageId: "P12",
      },
      {
        id: "P16",
        code: "P16",
        name: "Garlic Prawns",
        namePt: "Camarão com Alho",
        description: "Prawns, confit garlic, dry sherry, parsley.",
        descriptionPt: "Camarão, alho confitado, xerez seco, salsa.",
        price: 8.9,
        calories: 360,
        imageId: "P16",
      },
    ],
  },
  {
    id: "hotpot",
    label: "Panela de Fogo",
    labelJp: "火鍋",
    tagline: "Stone-warmed, table-side. Built to share.",
    dishes: [
      {
        id: "PF1",
        code: "PF1",
        name: "Prawn Hot Pot",
        namePt: "Panela de Camarão",
        description: "Prawns, tofu, cabbage, aromatic broth kept simmering.",
        descriptionPt: "Camarão, tofu, couve, caldo aromático a fervilhar.",
        price: 8.9,
        calories: 520,
        imageId: "PF1",
      },
      {
        id: "PF2",
        code: "PF2",
        name: "Beef Hot Pot",
        namePt: "Panela de Vaca",
        description: "Thin-sliced beef, bok choy, glass noodles, umami broth.",
        descriptionPt: "Vaca em fatias finas, pak choi, massa de vidro, caldo umami.",
        price: 8.9,
        calories: 610,
        imageId: "PF2",
      },
      {
        id: "PF3",
        code: "PF3",
        name: "Vegetable Hot Pot",
        namePt: "Panela Vegetal",
        description: "Shiitake, tofu, greens, enoki, kombu broth.",
        descriptionPt: "Shiitake, tofu, hortaliças, enoki, caldo de kombu.",
        price: 6.9,
        calories: 280,
        imageId: "PF3",
      },
    ],
  },
];

export const categoryById = (id: string) => menu.find((c) => c.id === id);
